---
- name: Set up Ethereum validator
  hosts: "{{ target }}"
  become: true
  gather_facts: false
  pre_tasks:
    - name: update and upgrade
      apt:
        upgrade: dist
        update_cache: true
  roles:
    - prepare
    - geth
    - node_exporter
    - process_exporter
    - lighthouse
