---
- name: Update Lighthouse
  hosts: '{{ target }}'
  become: true
  gather_facts: false
  pre_tasks:
    - name: stop beacon and validator services
      systemd:
        name: '{{ item }}'
        state: stopped
      changed_when: false
      loop:
        - lighthousebeacon
        - lighthousevalidator

  roles:
    - lighthouse

  post_tasks:
    - name: restart lighthousebeacon services
      systemd:
        name: '{{ item }}'
        state: restarted
      changed_when: false
      loop:
        - lighthousebeacon
        - lighthousevalidator
