---
- name: install packages
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: ufw already enabled
  command: ufw status verbose
  register: ufw_status_result
  changed_when: false

- name: Open Go Ethereum port 30303 TCP
  command: ufw allow 30303/tcp
  changed_when: false

- name: Open Go Ethereum port 30303 UDP
  command: ufw allow 30303/udp
  changed_when: false

- name: Open Beacon Chain p2p port 9000 TCP
  command: ufw allow 9000/tcp
  changed_when: false

- name: Open Beacon Chain p2p port 9000 UDP
  command: ufw allow 9000/udp
  changed_when: false

- name: open lighthouse port
  command: ufw allow 5054/tcp
  when:
    - not ufw_status_result.stdout is search("5054/tcp.*ALLOW IN.*Anywhere")

- name: open node_exporter port
  command: ufw allow 9100/tcp
  when:
    - node_exporter_enabled|default(false)|bool
    - not ufw_status_result.stdout is search("9100/tcp.*ALLOW IN.*Anywhere")

- name: open process_exporter port
  command: ufw allow 9256/tcp
  when:
    - process_exporter_enabled|default(false)|bool
    - not ufw_status_result.stdout is search("9256/tcp.*ALLOW IN.*Anywhere")

- name: enable firewall
  shell: |
    set -o pipefail
    echo "y" | ufw enable
  args:
    executable: /bin/bash
  when: not ufw_status_result.stdout is search("Status.* active")
